# Usa Node.js para build
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage final: servidor ligero con Nginx
FROM nginx:stable-alpine

# Copiar build de Vite a carpeta de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer puerto estándar HTTP
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
