# Generated by Django 4.2.21 on 2025-07-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataClient',
            fields=[
                ('cif', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('cod_client', models.CharField(editable=False, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataCompany',
            fields=[
                ('cif', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('num_presupuesto', models.CharField(max_length=13)),
                ('fecha_factalb', models.DateField(blank=True, null=True)),
                ('num_albaran', models.CharField(blank=True, max_length=13, null=True)),
                ('num_factura', models.CharField(blank=True, max_length=13, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('compr_albaran', models.CharField(blank=True, max_length=100, null=True)),
                ('datefactura', models.DateField(blank=True, null=True)),
                ('dataclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataclient', to='mi_app.dataclient')),
            ],
        ),
        migrations.CreateModel(
            name='titleDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titdescripcion', models.TextField()),
                ('titledoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titledocu', to='mi_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mi_app.datacompany')),
            ],
        ),
        migrations.CreateModel(
            name='FooterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('footer_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footerdocumentos', to='mi_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='DataDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('line', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_client', to='mi_app.document')),
            ],
        ),
        migrations.AddField(
            model_name='dataclient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mi_app.datacompany'),
        ),
    ]
