# Generated by Django 4.2.21 on 2025-09-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclient',
            name='province',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
