# Generated by Django 4.2.21 on 2025-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdocument',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='footerdocument',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='footerdocument',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
