# Generated by Django 4.2.21 on 2025-05-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadocument',
            name='cod_factura',
            field=models.ForeignKey(default='sin-factura', on_delete=django.db.models.deletion.CASCADE, related_name='cod_factura', to='mi_app.document'),
            preserve_default=False,
        ),
    ]
