# Generated by Django 4.2.21 on 2025-05-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_datadocument_cod_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacompany',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
