# Generated by Django 4.2.21 on 2026-01-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_dataclient_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titledescripcion',
            options={'verbose_name': 'Título de Sección'},
        ),
        migrations.AlterField(
            model_name='datadocument',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='datadocument',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mi_app.document'),
        ),
        migrations.AlterField(
            model_name='datadocument',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='datadocument',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='dataclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mi_app.dataclient'),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_presupuesto',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='footerdocument',
            name='footer_documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='mi_app.document'),
        ),
        migrations.AlterField(
            model_name='titledescripcion',
            name='titledoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='mi_app.document'),
        ),
    ]
