# Generated by Django 4.2.21 on 2026-01-17 04:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_titledescripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacompany',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterModelTable(
            name='dataclient',
            table='data_client',
        ),
        migrations.AlterModelTable(
            name='datacompany',
            table='data_company',
        ),
        migrations.AlterModelTable(
            name='datadocument',
            table='data_document',
        ),
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
        migrations.AlterModelTable(
            name='footerdocument',
            table='footer_document',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pago',
        ),
        migrations.AlterModelTable(
            name='titledescripcion',
            table='title_descripcion',
        ),
    ]
