# Generated by Django 4.2.21 on 2025-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_datacompany_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclient',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
