# Generated by Django 4.2.21 on 2026-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_datacompany_logo_alter_dataclient_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacompany',
            name='iva_comp',
            field=models.CharField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
