# Generated by Django 4.2.21 on 2025-05-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_dataclient_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadocument',
            name='cod_factura',
        ),
    ]
