# Generated by Django 4.2.21 on 2025-05-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_remove_datadocument_cod_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadocument',
            name='base_imponible',
        ),
        migrations.RemoveField(
            model_name='datadocument',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='datadocument',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='datadocument',
            name='total',
        ),
        migrations.CreateModel(
            name='FooterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('footer_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footerdocumentos', to='mi_app.document')),
            ],
        ),
    ]
