# Generated by Django 4.2.21 on 2025-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_remove_datadocument_base_imponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
