# Generated by Django 4.2.21 on 2025-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_alter_datadocument_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fecha_factura',
            field=models.DateField(),
        ),
    ]
