# Generated by Django 5.1.7 on 2025-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('addres_company', models.CharField(max_length=50)),
                ('zip_code_company', models.CharField(max_length=10)),
                ('city_company', models.CharField(max_length=50)),
                ('number_company', models.CharField(max_length=30)),
                ('nie_cif_dni_company', models.CharField(max_length=30)),
                ('email_company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_num', models.CharField(max_length=50)),
                ('data_documt', models.CharField(max_length=15)),
                ('data_cod_client', models.CharField(max_length=30)),
                ('data_observations', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=30)),
                ('client_addres', models.CharField(max_length=30)),
                ('client_zip_code', models.CharField(max_length=10)),
                ('client_city', models.CharField(max_length=20)),
                ('client_province', models.CharField(max_length=30)),
                ('client_nie_cif_dni', models.CharField(max_length=30)),
                ('payment_method', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_data_num', models.CharField(max_length=50)),
                ('doc_reference', models.CharField(max_length=30)),
                ('doc_description', models.CharField(max_length=30)),
                ('doc_amount', models.CharField(max_length=30)),
                ('doc_price', models.CharField(max_length=30)),
                ('doc_dto', models.CharField(max_length=30)),
                ('doc_import', models.CharField(max_length=30)),
                ('doc_subtotal', models.CharField(max_length=12)),
                ('doc_tax_base', models.CharField(max_length=12)),
                ('doc_iva', models.CharField(max_length=3)),
                ('doc_total', models.CharField(max_length=15)),
            ],
        ),
    ]
