# Generated by Django 5.1.7 on 2025-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('addres_company', models.CharField(max_length=50)),
                ('zip_code_company', models.TextField(blank=True)),
                ('city_company', models.CharField(max_length=50)),
                ('number_company', models.CharField(max_length=30)),
                ('nie_cif_dni_company', models.CharField(max_length=30)),
                ('email_company', models.CharField(max_length=30)),
            ],
        ),
    ]
