# Generated by Django 5.1.7 on 2025-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_company',
            name='zip_code_company',
            field=models.CharField(max_length=10),
        ),
    ]
