# Generated by Django 5.1.7 on 2025-04-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_iva',
            field=models.CharField(max_length=5),
        ),
    ]
