# Generated by Django 5.1.7 on 2025-04-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_company', '0002_alter_document_doc_iva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_data_num',
            new_name='data_num',
        ),
    ]
