FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema (solo GCC para compilar mysqlclient)
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements e instalar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código
COPY . .

# Hacer el script ejecutable
RUN chmod +x wait-for-db.sh

# Comando final: ejecutar el script Python
CMD ["./wait-for-db.sh"]